# export
module.exports = ['BooksAndReference'
                  'Business'
                  'DeveloperTools'
                  'Education'
                  'Entertainment'
                  'FoodAndDining'
                  'Games'
                  'GovernmentAndPolitics'
                  'HealthAndFitness'
                  'KidsAndFamily'
                  'Lifestyle'
                  'Medical'
                  'MultimediaDesign'
                  'Music'
                  'NavigationAndMaps'
                  'NewsAndWeather'
                  'PersonalFinance'
                  'Personalization'
                  'PhotoAndVideo'
                  'Productivity'
                  'Security'
                  'Shopping'
                  'Social'
                  'Sports'
                  'Travel'
                  'UtilitiesAndTools']