# export
module.exports =
  "186": "Afrikaans"
  "110": "Afrikaans (South Africa)"
  "187": "Albanian"
  "151": "Albanian (Albania)"
  "188": "Amharic"
  "111": "Amharic (Ethiopia)"
  "8": "Arabic"
  "266": "Arabic (Algeria)"
  "265": "Arabic (Bahrain)"
  "36": "Arabic (Egypt)"
  "268": "Arabic (Iraq)"
  "57": "Arabic (Israel)"
  "269": "Arabic (Jordan)"
  "270": "Arabic (Kuwait)"
  "271": "Arabic (Lebanon)"
  "444": "Arabic (Libya)"
  "272": "Arabic (Mauritania)"
  "445": "Arabic (Morocco)"
  "273": "Arabic (Oman)"
  "274": "Arabic (Palestinian Authority)"
  "275": "Arabic (Qatar)"
  "13": "Arabic (Saudi Arabia)"
  "276": "Arabic (Syria)"
  "446": "Arabic (Tunisia)"
  "264": "Arabic (United Arab Emirates)"
  "267": "Arabic (Western Sahara (Disputed))"
  "277": "Arabic (Yemen)"
  "189": "Armenian"
  "125": "Armenian (Armenia)"
  "190": "Assamese"
  "45": "Assamese (India)"
  "191": "Azerbaijani"
  "447": "Azerbaijani (Arabic)"
  "794": "Azerbaijani (Arabic) (Azerbaijan)"
  "448": "Azerbaijani (Cyrillic)"
  "795": "Azerbaijani (Cyrillic) (Azerbaijan)"
  "482": "Azerbaijani (Latin)"
  "112": "Azerbaijani (Latin) (Azerbaijan)"
  "194": "Bangla"
  "114": "Bangla (Bangladesh)"
  "46": "Bangla (India)"
  "518": "Bangla (Pakistan)"
  "192": "Basque"
  "119": "Basque (Basque)"
  "193": "Belarusian"
  "113": "Belarusian (Belarus)"
  "195": "Bosnian"
  "449": "Bosnian (Cyrillic)"
  "450": "Bosnian (Cyrillic) (Bosnia and Herzegovina)"
  "451": "Bosnian (Latin)"
  "115": "Bosnian (Latin) (Bosnia and Herzegovina)"
  "26": "Bulgarian"
  "27": "Bulgarian (Bulgaria)"
  "463": "Cajun French"
  "466": "Cajun French (Latin)"
  "197": "Catalan"
  "116": "Catalan (Spain)"
  "200": "Cherokee"
  "253": "Cherokee (Cherokee)"
  "118": "Cherokee (Cherokee) (United States)"
  "452": "Cherokee (Latin)"
  "99": "Cherokee (United States)"
  "2": "Chinese"
  "5": "Chinese (China)"
  "43": "Chinese (Hong Kong SAR)"
  "442": "Chinese (Macao SAR)"
  "262": "Chinese (Simplified)"
  "479": "Chinese (Simplified) (China)"
  "477": "Chinese (Simplified) (Singapore)"
  "176": "Chinese (Singapore)"
  "88": "Chinese (Taiwan)"
  "263": "Chinese (Traditional)"
  "481": "Chinese (Traditional) (Hong Kong)"
  "478": "Chinese (Traditional) (Macao SAR)"
  "480": "Chinese (Traditional) (Taiwan)"
  "31": "Croatian"
  "475": "Croatian (Bosnia and Herzegovina)"
  "32": "Croatian (Croatia)"
  "198": "Czech"
  "33": "Czech (Czech Republic)"
  "34": "Danish"
  "35": "Danish (Denmark)"
  "199": "Dari"
  "145": "Dari (Afghanistan)"
  "476": "Dari (Arabic)"
  "67": "Dutch"
  "178": "Dutch (Belgium)"
  "68": "Dutch (Netherlands)"
  "1": "English"
  "280": "English (Afghanistan)"
  "290": "English (Åland Islands)"
  "283": "English (Albania)"
  "526": "English (Algeria)"
  "288": "English (American Samoa)"
  "519": "English (Andorra)"
  "286": "English (Angola)"
  "282": "English (Anguilla)"
  "287": "English (Antarctica)"
  "281": "English (Antigua and Barbuda)"
  "284": "English (Armenia)"
  "289": "English (Aruba)"
  "824": "English (Australia and New Zealand)"
  "24": "English (Australia)"
  "291": "English (Azerbaijan)"
  "301": "English (Bahama"
  "520": "English (Bangladesh)"
  "293": "English (Barbados)"
  "305": "English (Belarus)"
  "453": "English (Belize)"
  "296": "English (Benin)"
  "298": "English (Bermuda)"
  "302": "English (Bhutan)"
  "522": "English (Bolivia)"
  "300": "English (Bonaire, Saint Eustatius and Saba)"
  "292": "English (Bosnia and Herzegovina)"
  "304": "English (Botswana)"
  "303": "English (Bouvet Island)"
  "339": "English (British Indian Ocean Territory)"
  "415": "English (British Virgin Islands)"
  "299": "English (Brunei)"
  "521": "English (Bulgaria)"
  "294": "English (Burkina Faso)"
  "295": "English (Burundi)"
  "344": "English (Cambodia)"
  "312": "English (Cameroon)"
  "28": "English (Canada)"
  "523": "English (Cape Verde)"
  "826": "English (Caribbean)"
  "348": "English (Cayman Islands)"
  "308": "English (Central African Republic)"
  "400": "English (Chad)"
  "314": "English (Christmas Island)"
  "306": "English (Cocos (Keeling) Islands)"
  "346": "English (Comoros)"
  "307": "English (Congo (DRC))"
  "309": "English (Congo)"
  "311": "English (Cook Islands)"
  "310": "English (Côte d'Ivoire)"
  "531": "English (Croatia)"
  "313": "English (Curaçao)"
  "315": "English (Djibouti)"
  "524": "English (Dominica)"
  "525": "English (Dominican Republic)"
  "829": "English (Eastern Africa)"
  "331": "English (Equatorial Guinea)"
  "316": "English (Eritrea)"
  "527": "English (Estonia)"
  "317": "English (Ethiopia)"
  "319": "English (Falkland Islands (Islas Malvinas))"
  "321": "English (Faroe Islands)"
  "318": "English (Fiji)"
  "324": "English (French Guiana)"
  "379": "English (French Polynesia)"
  "401": "English (French Southern and Antarctic Lands)"
  "322": "English (Gabon)"
  "329": "English (Gambia, The)"
  "323": "English (Georgia)"
  "528": "English (Germany)"
  "326": "English (Ghana)"
  "327": "English (Gibraltar)"
  "328": "English (Greenland)"
  "529": "English (Guadeloupe)"
  "333": "English (Guam)"
  "325": "English (Guernsey)"
  "330": "English (Guinea)"
  "334": "English (Guinea-Bissau)"
  "335": "English (Guyana)"
  "337": "English (Haiti)"
  "336": "English (Heard Island and McDonald Islands)"
  "530": "English (Honduras)"
  "183": "English (Hong Kong SAR)"
  "534": "English (Iceland)"
  "44": "English (India)"
  "454": "English (Indonesia)"
  "533": "English (Iraq)"
  "173": "English (Ireland)"
  "338": "English (Isle of Man)"
  "532": "English (Israel)"
  "341": "English (Jamaica)"
  "340": "English (Jersey)"
  "535": "English (Jordan)"
  "455": "English (Kazakhstan)"
  "342": "English (Kenya)"
  "345": "English (Kiribati)"
  "343": "English (Kyrgyzstan)"
  "349": "English (Laos)"
  "537": "English (Latvia)"
  "353": "English (Lesotho)"
  "352": "English (Liberia)"
  "354": "English (Libya)"
  "536": "English (Lithuania)"
  "538": "English (Macao SAR)"
  "360": "English (Macedonia, FYRO)"
  "358": "English (Madagascar)"
  "369": "English (Malawi)"
  "457": "English (Malaysia)"
  "368": "English (Maldives)"
  "361": "English (Mali)"
  "456": "English (Malta)"
  "359": "English (Marshall Islands)"
  "365": "English (Martinique)"
  "367": "English (Mauritius)"
  "420": "English (Mayotte)"
  "320": "English (Micronesia)"
  "356": "English (Moldova)"
  "355": "English (Monaco)"
  "363": "English (Mongolia)"
  "366": "English (Montserrat)"
  "370": "English (Mozambique)"
  "362": "English (Myanmar)"
  "371": "English (Namibia)"
  "377": "English (Nauru)"
  "376": "English (Nepal)"
  "285": "English (Netherlands Antilles (Former))"
  "69": "English (Netherlands)"
  "372": "English (New Caledonia)"
  "174": "English (New Zealand)"
  "540": "English (Nicaragua)"
  "373": "English (Niger)"
  "375": "English (Nigeria)"
  "378": "English (Niue)"
  "374": "English (Norfolk Island)"
  "825": "English (Northern America)"
  "364": "English (Northern Mariana Islands)"
  "541": "English (Oman)"
  "459": "English (Pakistan)"
  "383": "English (Palau)"
  "543": "English (Palestinian Authority)"
  "380": "English (Papua New Guinea)"
  "458": "English (Philippines)"
  "382": "English (Pitcairn Islands)"
  "542": "English (Puerto Rico)"
  "544": "English (Qatar)"
  "384": "English (Réunion)"
  "545": "English (Romania)"
  "385": "English (Rwanda)"
  "297": "English (Saint Barthélemy)"
  "389": "English (Saint Helena, Ascension and Tristan da Cunha)"
  "347": "English (Saint Kitts and Nevis)"
  "350": "English (Saint Lucia)"
  "357": "English (Saint Martin (French Part))"
  "381": "English (Saint Pierre and Miquelon)"
  "414": "English (Saint Vincent and the Grenadines)"
  "419": "English (Samoa)"
  "392": "English (San Marino)"
  "396": "English (São Tomé and Príncipe)"
  "393": "English (Senegal)"
  "387": "English (Seychelles)"
  "391": "English (Sierra Leone)"
  "181": "English (Singapore)"
  "397": "English (Sint Maarten (Dutch Part))"
  "547": "English (Slovakia)"
  "546": "English (Slovenia)"
  "386": "English (Solomon Islands)"
  "394": "English (Somalia)"
  "182": "English (South Africa)"
  "332": "English (South Georgia and the South Sandwich Islands)"
  "828": "English (Southern Africa)"
  "351": "English (Sri Lanka)"
  "388": "English (Sudan)"
  "395": "English (Suriname)"
  "390": "English (Svalbard and Jan Mayen)"
  "398": "English (Swaziland)"
  "403": "English (Tajikistan)"
  "410": "English (Tanzania)"
  "548": "English (Thailand)"
  "405": "English (Timor-Leste)"
  "402": "English (Togo)"
  "404": "English (Tokelau)"
  "407": "English (Tonga)"
  "408": "English (Trinidad and Tobago)"
  "549": "English (Turkey)"
  "406": "English (Turkmenistan)"
  "399": "English (Turks and Caicos Islands)"
  "409": "English (Tuvalu)"
  "796": "English (U.S. Minor Outlying Islands)"
  "416": "English (U.S. Virgin Islands)"
  "411": "English (Uganda)"
  "95": "English (United Kingdom)"
  "4": "English (United States)"
  "412": "English (Uzbekistan)"
  "417": "English (Vanuatu)"
  "413": "English (Vatican City)"
  "460": "English (Vietnam)"
  "418": "English (Wallis and Futuna)"
  "827": "English (Western Africa)"
  "421": "English (Zambia)"
  "422": "English (Zimbabwe)"
  "37": "Estonian"
  "38": "Estonian (Estonia)"
  "201": "Filipino"
  "461": "Filipino (Latin)"
  "121": "Filipino (Philippines)"
  "39": "Finnish"
  "40": "Finnish (Finland)"
  "471": "Franco-Provençal"
  "472": "Franco-Provençal (Latin)"
  "18": "French"
  "809": "French (Åland Islands)"
  "670": "French (Albania)"
  "697": "French (Algeria)"
  "673": "French (American Samoa)"
  "667": "French (Andorra)"
  "671": "French (Angola)"
  "669": "French (Anguilla)"
  "672": "French (Antarctica)"
  "668": "French (Antigua and Barbuda)"
  "674": "French (Aruba)"
  "675": "French (Azerbaijan)"
  "684": "French (Bahamas, The)"
  "677": "French (Barbados)"
  "175": "French (Belgium)"
  "687": "French (Belize)"
  "680": "French (Benin)"
  "681": "French (Bermuda)"
  "685": "French (Bhutan)"
  "683": "French (Bolivia)"
  "810": "French (Bonaire, Saint Eustatius and Saba)"
  "676": "French (Bosnia and Herzegovina)"
  "686": "French (Botswana)"
  "811": "French (Bouvet Island)"
  "812": "French (British Indian Ocean Territory)"
  "780": "French (British Virgin Islands)"
  "682": "French (Brunei)"
  "678": "French (Burkina Faso)"
  "679": "French (Burundi)"
  "467": "French (Cameroon)"
  "29": "French (Canada)"
  "692": "French (Cape Verde)"
  "833": "French (Caribbean)"
  "725": "French (Cayman Islands)"
  "689": "French (Central African Republic)"
  "769": "French (Chad)"
  "693": "French (Christmas Island)"
  "688": "French (Cocos (Keeling) Islands)"
  "723": "French (Comoros)"
  "464": "French (Congo (DRC))"
  "690": "French (Congo)"
  "691": "French (Cook Islands)"
  "465": "French (Côte d'Ivoire)"
  "813": "French (Curaçao)"
  "694": "French (Djibouti)"
  "695": "French (Dominica)"
  "696": "French (Dominican Republic)"
  "714": "French (Equatorial Guinea)"
  "698": "French (Eritrea)"
  "700": "French (Falkland Islands (Islas Malvinas))"
  "702": "French (Faroe Islands)"
  "699": "French (Fiji)"
  "19": "French (France)"
  "706": "French (French Guiana)"
  "751": "French (French Polynesia)"
  "703": "French (Gabon)"
  "711": "French (Gambia, The)"
  "705": "French (Georgia)"
  "708": "French (Ghana)"
  "709": "French (Gibraltar)"
  "710": "French (Greenland)"
  "704": "French (Grenada)"
  "713": "French (Guadeloupe)"
  "715": "French (Guam)"
  "707": "French (Guernsey)"
  "712": "French (Guinea)"
  "716": "French (Guinea-Bissau)"
  "717": "French (Guyana)"
  "468": "French (Haiti)"
  "814": "French (Heard Island and McDonald Islands)"
  "718": "French (Honduras)"
  "720": "French (Jamaica)"
  "719": "French (Jersey)"
  "722": "French (Kiribati)"
  "721": "French (Kyrgyzstan)"
  "726": "French (Laos)"
  "729": "French (Lesotho)"
  "728": "French (Liberia)"
  "730": "French (Libya)"
  "179": "French (Luxembourg)"
  "736": "French (Macao SAR)"
  "732": "French (Madagascar)"
  "742": "French (Malawi)"
  "741": "French (Maldives)"
  "470": "French (Mali)"
  "733": "French (Marshall Islands)"
  "738": "French (Martinique)"
  "740": "French (Mauritius)"
  "785": "French (Mayotte)"
  "701": "French (Micronesia)"
  "731": "French (Moldova)"
  "469": "French (Monaco)"
  "735": "French (Mongolia)"
  "739": "French (Montserrat)"
  "438": "French (Morocco)"
  "743": "French (Mozambique)"
  "734": "French (Myanmar)"
  "744": "French (Namibia)"
  "749": "French (Nauru)"
  "745": "French (New Caledonia)"
  "748": "French (Nicaragua)"
  "746": "French (Niger)"
  "750": "French (Niue)"
  "747": "French (Norfolk Island)"
  "462": "French (North Africa)"
  "834": "French (Northern America)"
  "737": "French (Northern Mariana Islands)"
  "756": "French (Palau)"
  "755": "French (Palestinian Authority)"
  "752": "French (Papua New Guinea)"
  "754": "French (Pitcairn Islands)"
  "473": "French (Réunion)"
  "757": "French (Rwanda)"
  "816": "French (Saint Barthélemy)"
  "760": "French (Saint Helena, Ascension and Tristan da Cunha)"
  "724": "French (Saint Kitts and Nevis)"
  "727": "French (Saint Lucia)"
  "817": "French (Saint Martin (French Part))"
  "753": "French (Saint Pierre and Miquelon)"
  "779": "French (Saint Vincent and the Grenadines)"
  "784": "French (Samoa)"
  "762": "French (San Marino)"
  "766": "French (São Tomé and Príncipe)"
  "763": "French (Senegal)"
  "759": "French (Seychelles)"
  "761": "French (Sierra Leone)"
  "818": "French (Sint Maarten (Dutch Part))"
  "758": "French (Solomon Islands)"
  "764": "French (Somalia)"
  "819": "French (South Georgia and the South Sandwich Islands)"
  "765": "French (Suriname)"
  "815": "French (Svalbard and Jan Mayen)"
  "767": "French (Swaziland)"
  "87": "French (Switzerland)"
  "771": "French (Tajikistan)"
  "776": "French (Tanzania)"
  "773": "French (Timor-Leste)"
  "770": "French (Togo)"
  "772": "French (Tokelau)"
  "774": "French (Tonga)"
  "439": "French (Tunisia)"
  "768": "French (Turks and Caicos Islands)"
  "775": "French (Tuvalu)"
  "820": "French (U.S. Minor Outlying Islands)"
  "781": "French (U.S. Virgin Islands)"
  "777": "French (Uganda)"
  "782": "French (Vanuatu)"
  "778": "French (Vatican City)"
  "783": "French (Wallis and Futuna)"
  "835": "French (Western Africa)"
  "832": "French (Western Europe)"
  "786": "French (Zambia)"
  "787": "French (Zimbabwe)"
  "81": "Galician"
  "82": "Galician (Spain)"
  "202": "Georgian"
  "130": "Georgian (Georgia)"
  "9": "German"
  "177": "German (Austria)"
  "14": "German (Germany)"
  "278": "German (Liechtenstein)"
  "180": "German (Luxembourg)"
  "86": "German (Switzerland)"
  "41": "Greek"
  "279": "Greek (Cyprus)"
  "42": "Greek (Greece)"
  "203": "Gujarati"
  "48": "Gujarati (India)"
  "254": "Hausa"
  "204": "Hausa (Latin)"
  "124": "Hausa (Latin) (Nigeria)"
  "55": "Hebrew"
  "56": "Hebrew (Israel)"
  "11": "Hindi"
  "16": "Hindi (India)"
  "104": "Hungarian"
  "105": "Hungarian (Hungary)"
  "205": "Icelandic"
  "128": "Icelandic (Iceland)"
  "206": "Igbo"
  "484": "Igbo (Latin)"
  "127": "Igbo (Nigeria)"
  "207": "Indonesian"
  "126": "Indonesian (Indonesia)"
  "196": "Inuktitut"
  "22": "Inuktitut (Canada)"
  "30": "Inuktitut (Canadian) Canada"
  "255": "Inuktitut (Latin)"
  "129": "Inuktitut (Latin) (Canada)"
  "208": "Irish"
  "122": "Irish (Ireland)"
  "209": "isiXhosa"
  "165": "isiXhosa (South Africa)"
  "210": "isiZulu"
  "167": "isiZulu (South Africa)"
  "58": "Italian"
  "59": "Italian (Italy)"
  "443": "Italian (Switzerland)"
  "12": "Japanese"
  "17": "Japanese (Japan)"
  "211": "Kannada"
  "52": "Kannada (India)"
  "212": "Kazakh"
  "131": "Kazakh (Kazakhstan)"
  "213": "Khmer"
  "132": "Khmer (Cambodia)"
  "516": "K'iche'"
  "901": "K'iche' (Guatemala)"
  "517": "K'iche' (Latin)"
  "215": "Kinyarwanda"
  "148": "Kinyarwanda (Rwanda)"
  "216": "Kiswahili"
  "154": "Kiswahili (Kenya)"
  "217": "Konkani"
  "54": "Konkani (India)"
  "60": "Korean"
  "61": "Korean (Korea)"
  "218": "Kurdish"
  "256": "Kurdish (Arabic)"
  "133": "Kurdish (Iraq)"
  "219": "Kyrgyz"
  "485": "Kyrgyz (Cyrillic)"
  "134": "Kyrgyz (Kyrgyzstan)"
  "903": "Lao"
  "902": "Lao (Laos)"
  "62": "Latvian"
  "63": "Latvian (Latvia)"
  "64": "Lithuanian"
  "65": "Lithuanian (Lithuania)"
  "220": "Luxembourgish"
  "135": "Luxembourgish (Luxembourg)"
  "221": "Macedonian"
  "137": "Macedonian (Macedonia, FYRO)"
  "222": "Malay"
  "490": "Malay (Brunei)"
  "140": "Malay (Malaysia)"
  "223": "Malayalam"
  "53": "Malayalam (India)"
  "224": "Maltese"
  "141": "Maltese (Malta)"
  "225": "Maori"
  "486": "Maori (Latin)"
  "136": "Maori (New Zealand)"
  "226": "Marathi"
  "139": "Marathi (India)"
  "227": "Mongolian"
  "487": "Mongolian (Cyrillic)"
  "138": "Mongolian (Mongolia)"
  "488": "Mongolian (Mongolian)"
  "489": "Mongolian (Phags-pa)"
  "228": "Nepali"
  "142": "Nepali (Nepal)"
  "491": "Norwegian"
  "229": "Norwegian (Bokmål)"
  "70": "Norwegian (Bokmål) (Norway)"
  "492": "Norwegian (Norway)"
  "230": "Norwegian (Nynorsk)"
  "71": "Norwegian (Nynorsk) (Norway)"
  "231": "Odia"
  "49": "Odia (India)"
  "232": "Persian/Farsi"
  "120": "Persian/Farsi  (Iran)"
  "72": "Polish"
  "73": "Polish (Poland)"
  "25": "Portuguese"
  "74": "Portuguese (Brazil)"
  "75": "Portuguese (Portugal)"
  "3": "Pseudo"
  "6": "Pseudoloc"
  "823": "Pseudoloc (Latin) (Selfhost)"
  "900": "Pseudoloc East Asian-language"
  "7": "Pseudoloc Mirrored"
  "233": "Punjabi"
  "257": "Punjabi (Arabic)"
  "493": "Punjabi (Devanagari)"
  "47": "Punjabi (India)"
  "144": "Punjabi (Pakistan)"
  "234": "Quechua"
  "495": "Quechua (Bolivia)"
  "496": "Quechua (Ecuador)"
  "147": "Quechua (Peru)"
  "76": "Romanian"
  "77": "Romanian (Romania)"
  "788": "Russian (Armenia)"
  "789": "Russian (Belarus)"
  "790": "Russian (Kazakhstan)"
  "791": "Russian (Ukraine)"
  "235": "Scottish Gaelic"
  "474": "Scottish Gaelic (Latin)"
  "123": "Scottish Gaelic (United Kingdom)"
  "236": "Serbian"
  "259": "Serbian (Cyrillic)"
  "152": "Serbian (Cyrillic) (Bosnia and Herzegovina)"
  "498": "Serbian (Cyrillic) (Montenegro)"
  "440": "Serbian (Cyrillic) (Serbia )"
  "153": "Serbian (Cyrillic) (Serbia and Montenegro, Former)"
  "100": "Serbian (Latin)"
  "499": "Serbian (Latin) (Bosnia and Herzegovina)"
  "441": "Serbian (Latin) (Montenegro)"
  "101": "Serbian (Latin) (Serbia and Montenegro (Former))"
  "500": "Serbian (Latin) (Serbia)"
  "237": "Sesotho sa Leboa"
  "143": "Sesotho sa Leboa (South Africa)"
  "238": "Setswana"
  "507": "Setswana (Botswana)"
  "158": "Setswana (South Africa)"
  "239": "Sindhi"
  "258": "Sindhi (Arabic)"
  "497": "Sindhi (Devanagari)"
  "149": "Sindhi (Pakistan)"
  "240": "Sinhala"
  "150": "Sinhala (Sri Lanka)"
  "78": "Slovak"
  "79": "Slovak (Slovakia)"
  "102": "Slovenian"
  "792": "Slovenian (Sierra Leone)"
  "103": "Slovenian (Slovenia)"
  "10": "Spanish"
  "797": "Spanish (Åland Islands)"
  "552": "Spanish (Albania)"
  "555": "Spanish (American Samoa)"
  "830": "Spanish (Americas)"
  "423": "Spanish (Andorra)"
  "553": "Spanish (Angola)"
  "551": "Spanish (Anguilla)"
  "554": "Spanish (Antarctica)"
  "550": "Spanish (Antigua and Barbuda)"
  "23": "Spanish (Argentina)"
  "556": "Spanish (Aruba)"
  "557": "Spanish (Azerbaijan)"
  "565": "Spanish (Bahamas, The)"
  "559": "Spanish (Barbados)"
  "425": "Spanish (Belize)"
  "562": "Spanish (Benin)"
  "563": "Spanish (Bermuda)"
  "566": "Spanish (Bhutan)"
  "424": "Spanish (Bolivia)"
  "798": "Spanish (Bonaire, Saint Eustatius and Saba)"
  "558": "Spanish (Bosnia and Herzegovina)"
  "567": "Spanish (Botswana)"
  "799": "Spanish (Bouvet Island)"
  "800": "Spanish (British Indian Ocean Territory)"
  "659": "Spanish (British Virgin Islands)"
  "564": "Spanish (Brunei)"
  "560": "Spanish (Burkina Faso)"
  "561": "Spanish (Burundi)"
  "574": "Spanish (Cameroon)"
  "80": "Spanish (Canada)"
  "428": "Spanish (Cape Verde)"
  "602": "Spanish (Cayman Islands)"
  "570": "Spanish (Central African Republic)"
  "648": "Spanish (Chad)"
  "184": "Spanish (Chile)"
  "575": "Spanish (Christmas Island)"
  "568": "Spanish (Cocos (Keeling) Islands)"
  "185": "Spanish (Colombia)"
  "600": "Spanish (Comoros)"
  "569": "Spanish (Congo (DRC))"
  "571": "Spanish (Congo)"
  "573": "Spanish (Cook Islands)"
  "426": "Spanish (Costa Rica)"
  "572": "Spanish (Côte d'Ivoire)"
  "427": "Spanish (Cuba)"
  "801": "Spanish (Curaçao)"
  "576": "Spanish (Djibouti)"
  "429": "Spanish (Dominica)"
  "430": "Spanish (Dominican Republic)"
  "169": "Spanish (Ecuador)"
  "172": "Spanish (El Salvador)"
  "591": "Spanish (Equatorial Guinea)"
  "577": "Spanish (Eritrea)"
  "83": "Spanish (EU)"
  "579": "Spanish (Falkland Islands (Islas Malvinas))"
  "581": "Spanish (Faroe Islands)"
  "578": "Spanish (Fiji)"
  "584": "Spanish (French Guiana)"
  "629": "Spanish (French Polynesia)"
  "582": "Spanish (Gabon)"
  "589": "Spanish (Gambia, The)"
  "583": "Spanish (Georgia)"
  "586": "Spanish (Ghana)"
  "587": "Spanish (Gibraltar)"
  "588": "Spanish (Greenland)"
  "431": "Spanish (Grenada)"
  "432": "Spanish (Guadeloupe)"
  "592": "Spanish (Guam)"
  "171": "Spanish (Guatemala)"
  "585": "Spanish (Guernsey)"
  "590": "Spanish (Guinea)"
  "593": "Spanish (Guinea-Bissau)"
  "594": "Spanish (Guyana)"
  "595": "Spanish (Haiti)"
  "802": "Spanish (Heard Island and McDonald Islands)"
  "170": "Spanish (Honduras)"
  "597": "Spanish (Jamaica)"
  "596": "Spanish (Jersey)"
  "599": "Spanish (Kiribati)"
  "598": "Spanish (Kyrgyzstan)"
  "603": "Spanish (Laos)"
  "831": "Spanish (Latin America and the Caribbean)"
  "606": "Spanish (Lesotho)"
  "605": "Spanish (Liberia)"
  "607": "Spanish (Libya)"
  "615": "Spanish (Macao SAR)"
  "610": "Spanish (Madagascar)"
  "621": "Spanish (Malawi)"
  "620": "Spanish (Maldives)"
  "612": "Spanish (Mali)"
  "611": "Spanish (Marshall Islands)"
  "617": "Spanish (Martinique)"
  "619": "Spanish (Mauritius)"
  "664": "Spanish (Mayotte)"
  "66": "Spanish (Mexico)"
  "580": "Spanish (Micronesia)"
  "609": "Spanish (Moldova)"
  "608": "Spanish (Monaco)"
  "614": "Spanish (Mongolia)"
  "618": "Spanish (Montserrat)"
  "622": "Spanish (Mozambique)"
  "613": "Spanish (Myanmar)"
  "623": "Spanish (Namibia)"
  "627": "Spanish (Nauru)"
  "624": "Spanish (New Caledonia)"
  "433": "Spanish (Nicaragua)"
  "625": "Spanish (Niger)"
  "628": "Spanish (Niue)"
  "626": "Spanish (Norfolk Island)"
  "616": "Spanish (Northern Mariana Islands)"
  "634": "Spanish (Palau)"
  "633": "Spanish (Palestinian Authority)"
  "168": "Spanish (Panama)"
  "630": "Spanish (Papua New Guinea)"
  "435": "Spanish (Paraguay)"
  "434": "Spanish (Peru)"
  "632": "Spanish (Pitcairn Islands)"
  "483": "Spanish (Puerto Rico)"
  "635": "Spanish (Réunion)"
  "636": "Spanish (Rwanda)"
  "804": "Spanish (Saint Barthélemy)"
  "639": "Spanish (Saint Helena, Ascension and Tristan da Cunha)"
  "601": "Spanish (Saint Kitts and Nevis)"
  "604": "Spanish (Saint Lucia)"
  "805": "Spanish (Saint Martin (French Part))"
  "631": "Spanish (Saint Pierre and Miquelon)"
  "658": "Spanish (Saint Vincent and the Grenadines)"
  "663": "Spanish (Samoa)"
  "641": "Spanish (San Marino)"
  "645": "Spanish (São Tomé and Príncipe)"
  "642": "Spanish (Senegal)"
  "638": "Spanish (Seychelles)"
  "640": "Spanish (Sierra Leone)"
  "806": "Spanish (Sint Maarten (Dutch Part))"
  "637": "Spanish (Solomon Islands)"
  "643": "Spanish (Somalia)"
  "807": "Spanish (South Georgia and the South Sandwich Islands)"
  "15": "Spanish (Spain)"
  "644": "Spanish (Suriname)"
  "803": "Spanish (Svalbard and Jan Mayen)"
  "646": "Spanish (Swaziland)"
  "650": "Spanish (Tajikistan)"
  "655": "Spanish (Tanzania)"
  "652": "Spanish (Timor-Leste)"
  "649": "Spanish (Togo)"
  "651": "Spanish (Tokelau)"
  "653": "Spanish (Tonga)"
  "647": "Spanish (Turks and Caicos Islands)"
  "654": "Spanish (Tuvalu)"
  "808": "Spanish (U.S. Minor Outlying Islands)"
  "660": "Spanish (U.S. Virgin Islands)"
  "656": "Spanish (Uganda)"
  "98": "Spanish (United States)"
  "436": "Spanish (Uruguay)"
  "661": "Spanish (Vanuatu)"
  "657": "Spanish (Vatican City)"
  "437": "Spanish (Venezuela)"
  "662": "Spanish (Wallis and Futuna)"
  "665": "Spanish (Zambia)"
  "666": "Spanish (Zimbabwe)"
  "84": "Swedish"
  "501": "Swedish (Finland)"
  "85": "Swedish (Sweden)"
  "241": "Tajik"
  "502": "Tajik (Arabic)"
  "260": "Tajik (Cyrillic)"
  "503": "Tajik (Latin)"
  "155": "Tajik (Tajikistan)"
  "242": "Tamil"
  "50": "Tamil (India)"
  "243": "Tatar"
  "508": "Tatar (Arabic)"
  "509": "Tatar (Cyrillic)"
  "510": "Tatar (Latin)"
  "159": "Tatar (Russia)"
  "244": "Telugu"
  "51": "Telugu (India)"
  "89": "Thai"
  "90": "Thai (Thailand)"
  "245": "Tigrinya"
  "156": "Tigrinya (Ethiopia)"
  "91": "Turkish"
  "92": "Turkish (Turkey)"
  "246": "Turkmen"
  "504": "Turkmen (Cyrillic)"
  "821": "Turkmen (Cyrillic) (Turkey)"
  "505": "Turkmen (Latin)"
  "822": "Turkmen (Latin) (Turkey)"
  "506": "Turkmen (Turkey)"
  "157": "Turkmen (Turkmenistan)"
  "93": "Ukrainian"
  "94": "Ukrainian (Ukraine)"
  "247": "Urdu"
  "161": "Urdu (Pakistan)"
  "248": "Uyghur"
  "511": "Uyghur (Arabic)"
  "160": "Uyghur (China)"
  "512": "Uyghur (Cyrillic)"
  "513": "Uyghur (Latin)"
  "249": "Uzbek"
  "514": "Uzbek (Cyrillic)"
  "261": "Uzbek (Latin)"
  "162": "Uzbek (Latin) (Uzbekistan)"
  "793": "Uzbek (Uzbekistan)"
  "117": "Valencian"
  "250": "Vietnamese"
  "163": "Vietnamese (Vietnam)"
  "96": "Welsh"
  "97": "Welsh (United Kingdom)"
  "251": "Wolof"
  "164": "Wolof (Senegal)"
  "252": "Yoruba"
  "515": "Yoruba (Latin)"
  "166": "Yoruba (Nigeria)"